import React, { useState } from 'react';
import { View, Text, StyleSheet, TextInput, TouchableOpacity, ScrollView } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';

export default function AuthScreen({ navigation }) {
  const [mode,setMode]=useState('signin'); const [secure,setSecure]=useState(true);
  const signIn=mode==='signin';
  return <SafeAreaView style={s.container}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Text style={s.logo}>VISIONFIT</Text><View style={s.form}><Text style={s.eyebrow}>{signIn?'WELCOME BACK':'START YOUR STYLE JOURNEY'}</Text><Text style={s.title}>{signIn?'Sign in':'Create account'}</Text><Text style={s.subtitle}>{signIn?'Continue to your personal eyewear edit.':'Create a profile to save your favorite frames.'}</Text><TextInput style={s.input} placeholder="Email address" placeholderTextColor="#798078" keyboardType="email-address" autoCapitalize="none"/><View style={s.passwordRow}><TextInput style={s.passwordInput} placeholder="Password" placeholderTextColor="#798078" secureTextEntry={secure}/><TouchableOpacity onPress={()=>setSecure(!secure)} hitSlop={10}><Ionicons name={secure?'eye-off-outline':'eye-outline'} color="#3E4841" size={20}/></TouchableOpacity></View>{!signIn&&<><TextInput style={s.input} placeholder="First name" placeholderTextColor="#798078"/><TextInput style={s.input} placeholder="Last name" placeholderTextColor="#798078"/></>}<TouchableOpacity style={s.button} onPress={()=>navigation.replace('MainTabs')}><Text style={s.buttonText}>{signIn?'Sign in':'Create account'}</Text><Ionicons name="arrow-forward" size={18} color="#171717"/></TouchableOpacity>{signIn?<TouchableOpacity><Text style={s.forgot}>Forgot password?</Text></TouchableOpacity>:<View style={s.switchLine}><Text style={s.switchText}>Already have an account? </Text><TouchableOpacity onPress={()=>setMode('signin')}><Text style={s.link}>Sign in</Text></TouchableOpacity></View>}{signIn&&<View style={s.switchLine}><Text style={s.switchText}>New to VisionFit? </Text><TouchableOpacity onPress={()=>setMode('signup')}><Text style={s.link}>Create account</Text></TouchableOpacity></View>}</View></ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({container:{flex:1,backgroundColor:'#fff'},content:{flexGrow:1,paddingHorizontal:24,paddingTop:54,paddingBottom:34},logo:{fontSize:30,fontWeight:'900',letterSpacing:-1.4,color:'#111'},form:{marginTop:58},eyebrow:{fontSize:11,fontWeight:'800',letterSpacing:1.1,color:'#7B687F',marginBottom:9},title:{fontSize:34,fontWeight:'800',letterSpacing:-.8,color:'#111'},subtitle:{fontSize:14,color:'#6E756F',lineHeight:20,marginTop:8,marginBottom:28},input:{height:52,backgroundColor:'#F1F3F4',borderWidth:1,borderColor:'#D7DBD8',borderRadius:12,paddingHorizontal:15,fontSize:15,color:'#111',marginBottom:13},passwordRow:{height:52,backgroundColor:'#F1F3F4',borderWidth:1,borderColor:'#D7DBD8',borderRadius:12,paddingHorizontal:15,flexDirection:'row',alignItems:'center',marginBottom:13},passwordInput:{flex:1,fontSize:15,color:'#111',paddingVertical:0},button:{height:52,borderRadius:14,backgroundColor:'#DCCBEF',alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8,marginTop:10},buttonText:{fontSize:15,fontWeight:'800',color:'#171717'},forgot:{textAlign:'center',fontSize:14,fontWeight:'600',color:'#252525',marginTop:18},switchLine:{flexDirection:'row',justifyContent:'center',alignItems:'center',marginTop:24},switchText:{fontSize:14,color:'#333'},link:{fontSize:14,fontWeight:'700',color:'#6C3BC6'}});
