import React from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';

function Glasses({ color }) { return <View style={styles.glasses}><View style={[styles.lens,{borderColor:color}]}/><View style={[styles.bridge,{backgroundColor:color}]}/><View style={[styles.lens,{borderColor:color}]}/></View>; }
function Pick({ color, name }) { return <TouchableOpacity style={styles.product}><TouchableOpacity style={styles.heart}><Ionicons name="heart-outline" size={17} color="#222" /></TouchableOpacity><View style={styles.frameArt}><Glasses color={color}/></View><Text style={styles.name}>{name}</Text><Text style={styles.price}>₱999</Text><View style={styles.swatches}><View style={[styles.dot,{backgroundColor:color}]}/><View style={[styles.dot,{backgroundColor:'#1BB5A5'}]}/><View style={[styles.dot,{backgroundColor:'#346EAF'}]}/></View></TouchableOpacity> }
export default function FavoritesScreen({ navigation }) { return <SafeAreaView style={styles.container} edges={['top']}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Text style={styles.title}>Favorites</Text><TouchableOpacity><Text style={styles.edit}>Edit</Text></TouchableOpacity></View><View style={styles.empty}><Ionicons name="heart-outline" size={104} color="#222"/><Text style={styles.emptyTitle}>Your saved frames will live here.</Text><Text style={styles.emptyText}>Explore the collection and tap the heart on any frame you love.</Text><TouchableOpacity style={styles.cta} onPress={() => navigation.navigate('Category')}><Text style={styles.ctaText}>Discover frames</Text></TouchableOpacity></View><View style={styles.recommendation}><Text style={styles.recommendationLabel}>YOU MIGHT ALSO LIKE</Text><View style={styles.products}><Pick color="#197A72" name="Margaret"/><Pick color="#C94D6B" name="Mia"/></View></View></ScrollView></SafeAreaView> }
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#F8F8F8'},content:{paddingBottom:28},header:{height:57,backgroundColor:'#fff',paddingHorizontal:19,alignItems:'center',justifyContent:'space-between',flexDirection:'row',borderBottomWidth:1,borderBottomColor:'#E5E5E5'},title:{fontSize:17,fontWeight:'800',color:'#171717'},edit:{fontSize:13,color:'#595959'},empty:{alignItems:'center',paddingHorizontal:36,paddingTop:67,paddingBottom:37},emptyTitle:{fontSize:17,fontWeight:'800',color:'#222',marginTop:18},emptyText:{fontSize:13,color:'#666',textAlign:'center',lineHeight:19,marginTop:8},cta:{height:44,alignSelf:'stretch',borderRadius:24,backgroundColor:'#000',alignItems:'center',justifyContent:'center',marginTop:23},ctaText:{fontSize:14,fontWeight:'800',color:'#fff'},recommendation:{backgroundColor:'#fff',padding:18,borderTopWidth:1,borderTopColor:'#E2E2E2'},recommendationLabel:{fontSize:10,fontWeight:'800',letterSpacing:.8,color:'#555',textAlign:'center',marginBottom:13},products:{flexDirection:'row',gap:12},product:{flex:1,height:175,borderWidth:1,borderColor:'#555',borderRadius:7,overflow:'hidden',padding:8},heart:{position:'absolute',right:7,top:7,zIndex:2},frameArt:{height:86,backgroundColor:'#EEF2F1',marginHorizontal:-8,marginTop:-8,alignItems:'center',justifyContent:'center'},glasses:{flexDirection:'row',alignItems:'center'},lens:{height:28,width:42,borderWidth:3,borderRadius:10},bridge:{height:3,width:10},name:{fontSize:12,fontWeight:'700',marginTop:9,color:'#222'},price:{fontSize:11,color:'#333',marginTop:2},swatches:{flexDirection:'row',gap:5,marginTop:6},dot:{height:10,width:10,borderRadius:5}});
